name: potoo-ldap-phonebook
namespace: sparrow
version: 1.0.3
author: Benoît Stahl
display_name: Potoo ldap phonebook 🦉
description: ⚡️ This plugin allow expose wazo directory through ldap
homepage: https://github.com/benasse/potoo-ldap-phonebook
